/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Details: typeof import('./src/components/subject/details/Details.vue')['default'];
    DetailsItem: typeof import('./src/components/subject/details/DetailsItem.vue')['default'];
    History: typeof import('./src/components/trade/history/History.vue')['default'];
    HistoryItem: typeof import('./src/components/trade/history/HistoryItem.vue')['default'];
    Message: typeof import('./src/components/message/Message.vue')['default'];
    NButton: typeof import('naive-ui')['NButton'];
    NCol: typeof import('naive-ui')['NCol'];
    NDialogProvider: typeof import('naive-ui')['NDialogProvider'];
    NDropdown: typeof import('naive-ui')['NDropdown'];
    NForm: typeof import('naive-ui')['NForm'];
    NFormItem: typeof import('naive-ui')['NFormItem'];
    NInput: typeof import('naive-ui')['NInput'];
    NMessageProvider: typeof import('naive-ui')['NMessageProvider'];
    NRow: typeof import('naive-ui')['NRow'];
    NSelect: typeof import('naive-ui')['NSelect'];
    Option: typeof import('./src/components/Option.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    Score: typeof import('./src/components/subject/score/Score.vue')['default'];
    Subject: typeof import('./src/components/subject/Subject.vue')['default'];
    SubjectBar: typeof import('./src/components/subject/SubjectBar.vue')['default'];
    SymbolIcon: typeof import('./src/components/symbolIcon/SymbolIcon.vue')['default'];
    Trade: typeof import('./src/components/trade/Trade.vue')['default'];
    TradeHeader: typeof import('./src/components/trade/TradeHeader.vue')['default'];
    Trend: typeof import('./src/components/trend/Trend.vue')['default'];
  }
}
